language: go
go:
- 1.7.x
sudo: false
install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/labstack/echo
  - go get github.com/gin-gonic/gin
  - go get github.com/gorilla/mux
  - go get github.com/julienschmidt/httprouter
